version: '3.0'


services:
  frontend:
    volumes:
      - ./nginx/logs/:/etc/nginx/logs/
      - ./nginx/ssl/:/etc/ssl/info1/
      - ./nginx/conf-analytics.nginx:/etc/nginx/nginx.conf
      - ./frontend-config/keycloak-prod.json:/usr/share/nginx/html/keycloak-prod.json
      - ./frontend-config/mime.types:/etc/nginx/mime.types
    depends_on:
      - analytics-backend
      - analytics-frontend
  analytics-backend:
    image: hoal/analytics-backend:master
    expose:
      - 4000
    environment:
      MONGO_DB_USERNAME: ${ANALYTICS_MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${ANALYTICS_MONGO_DB_PASSWORD}
    restart: always
    depends_on:
      - mongo
  analytics-frontend:
    image: hoal/analytics-frontend:master
    expose:
      - 80
    restart: always