version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      container_name: keycloak-db
      hostname: postgres
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
  mailhog:
      container_name: email-server
      image: mailhog/mailhog
      hostname: mailhog
      ports:
        - 1025:1025
        - 8025:8025
  keycloak:
      container_name: idp
      hostname: idp
      image: jboss/keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: ${DB_USER}
        DB_SCHEMA: public
        DB_PASSWORD: ${DB_PASSWORD}
        KEYCLOAK_USER: ${KEYCLOAK_USER}
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 9999:8080
      depends_on:
        - postgres
        - mailhog
      command:
      - "-b 0.0.0.0"
      #- "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/jboss/keycloak/realm-config.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
      volumes:
        - ./keycloak-configs/keycloak-export.json:/opt/jboss/keycloak/realm-config.json
      links:
        - "mailhog:email.server"
  course-service:
      image: hoal/course-service
      container_name: course-service
      ports:
        - 8080:8080
      depends_on:
        - keycloak
  nginx:
      image: nginx:latest
      container_name: reverse-proxy
      volumes:
        - ./nginx/conf.nginx:/etc/nginx/nginx.conf
        - ./nginx/error.log:/etc/nginx/error_log.log
        - ./nginx/access.log:/etc/nginx/nginx-access.log
      ports:
        - 80:80
        - 443:443
      links:
        - "course-service:api"
        - "keycloak:idp"
      depends_on:
        - course-service
