version: 2
jobs:
  deploy:
    docker:
      - image: kroniak/ssh-client
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fe:b1:c8:73:4c:fd:f9:6f:b9:84:56:6a:bc:ad:03:c8"
      - run:
          name: Deploy Over SSH
          command: |
            chmod u+x /root/access/infrastructure/scripts/restart-containers-do.sh
            ssh -o StrictHostKeyChecking=no $DIGITAL_OCEAN_USER@$DIGITAL_OCEAN_HOST "git pull && sh /root/access/infrastructure/scripts/restart-containers-do.sh"

workflows:
  version: 2
  deploy-infrastructure:
    jobs:
      - deploy:
          filters:
            branches:
              only: master