version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh -o StrictHostKeyChecking=no $DIGITAL_OCEAN_USER@$DIGITAL_OCEAN_HOST "cd /root/access/infrastructure && git pull && sh ./scripts/restart-containers"

workflows:
  version: 2
  deploy-infrastructure:
    jobs:
      - deploy:
          filters:
            branches:
              only: master